# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Long's datablog
tagline:          'A pythonic way from astrophysics to data science'
url:              http://www.ldocao.github.io
shorturl:         ldocao.github.io

author:
  name:           'Long Do Cao'
  url:            https://twitter.com/ldocao

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/ldocao/ldocao.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
