# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Long's story
tagline:             A pythonic way from astrophysics to data scientist
url:                 http://ldocao.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Long Do Cao
  url:               https://twitter.com/ldocao
  email:             ldocao@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/ldocao/ldocao.github.io
