# Site settings
title: Long's datablog
email: ldocao@gmail.com
url: https://ldocao.github.io
description: "From astrophysics to data science, the pythonic way."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Long Do Cao

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/ldocao
  - title: linkedin
    url: https://fr.linkedin.com/in/ldocao
  - title: github
    url: https://github.com/ldocao

# Build settings
markdown: kramdown
permalink: pretty
