# Welcome to Jekyll!
#

# Site settings
title: Krystals
description: Reliable & Elegant AI
owner: Long Do Cao
first_published: 2019
email: ldocao@krystals.ai
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://krystals.ai" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/krystals-ai
  linkedin-square: https://www.linkedin.com/company/krystals-ai/about/
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
